django_pjt2/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),

]

django_pjt2/django_pjt2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
]

django_pjt2/community/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=30)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django_pjt2/community/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields= '__all__'

django_pjt2/community/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews': reviews
    }
    return render(request,'community/review_list.html',context)

def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            Review = form.save()
            return redirect('community:index')
    else:
        form = ReviewForm()
    context = {
        'form':form
    }
    return render(request,'community/form.html',context)




def detail(request,id):
    # review = Review.objects.get(id=id)
    review = get_object_or_404(Review,id=id)
    context = {
        'review':review
    }
    return render(request,'community/review_detail.html',context)



def update(request,id):
    review = get_object_or_404(Review,id=id)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('community:detail', id)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form':form
    }
    return render(request, 'community/form.html',context)


@require_POST
def delete(request,id):
    review = get_object_or_404(Review,id=id)
    review.delete()
    return redirect('community:index')

django_pjt2/community/templates/community/form.html
{% extends 'base.html' %}
{% block body %}
    <div class="text-center">
        <h1>새로운 Review를 작성해 보셔요 ^^</h1>
        <form action = "" method="POST">
            {% csrf_token %}
            <p>TITLE<br>{{ form.title }}</p>
            <p>MOVIE_TITLE<br>{{ form.movie_title }}</p>
            <p>RANK(1 to 5)<br>{{ form.rank }}</p>
            <p>CONTENT<br>{{ form.content }}</p>
            <input type="submit">
        </form>
    </div>
{% endblock %}

django_pjt2/community/templates/community/review_detail.html
{% extends 'base.html' %}
{% block body %}
    <h1>DETAIL 페이지</h1>
    Title : {{review.title}}<br>
    Movie_title : {{review.movie_title}}<br>
    rank : {{review.rank}}<br>
    created_at : {{review.created_at}}<br>
    updated_at : {{review.updated_at}}<br>
    <form action="{% url 'community:update' review.id %}">
        <button>글 수정</button>
    </form>
    <form action="{% url 'community:delete' review.pk %}" method="POST">
        {% csrf_token %}
        <button>글 삭제</button>
    </form>
    <a href="/community">Home으로</a>
{% endblock %}

django_pjt2/community/templates/community/review_list.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center bg-success mb-0">군대영화 COMMUNITY</h1>
    <table class="table text-center">
      <thead class="thead-dark">
        <tr>
          <th scope="col">글 번호</th>
          <th scope="col">글 제목</th>
          <th scope="col">영화 이름</th>
          <th scope="col">최종작성시간</th>
        </tr>
      </thead>
      <tbody>
    {% for review in reviews %}
        <tr>
          <th scope="row"> <a href="{% url 'community:detail' review.id %}">{{forloop.counter}}</a><br></th>
          <td>{{review.title}}</td>
          <td>{{review.movie_title}}</td>
          <td>{{review.updated_at}}</td>
        </tr>

    {% endfor %}
      </tbody>
    </table>
    <div class="text-center">
        <img alt="대한민국 육군 마스코트 호국이 [육군 조교 동생] : 네이버 블로그" class="n3VNCb" src="https://lh3.googleusercontent.com/proxy/L7uzqARBZ7GsyaXBwOJx3DjoP5QlmrPmHOhRmbtJHqFMmWDqTNxrrQIshpXpxIHij8Fqisntj7eDkD3AQLixag2wEEn7FbBf9t3IEgJ0xuHq817g-zS8z5i0R2gIo5HR-vhAHiz73pImPEI2Xcnff3Sc7BAwqLsW5NwkUV7_ADX8L38N7A" data-noaft="1" jsname="HiaYvf" jsaction="load:XAeZkd;" style="width: 400px; height: 400px; margin: 0px;">
    </div>



{% endblock %}

django_pjt2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <a class="navbar-brand" href="/community"><img alt="대한민국 육군 마스코트 호국이 [육군 조교 동생] : 네이버 블로그" class="n3VNCb" src="https://lh3.googleusercontent.com/proxy/L7uzqARBZ7GsyaXBwOJx3DjoP5QlmrPmHOhRmbtJHqFMmWDqTNxrrQIshpXpxIHij8Fqisntj7eDkD3AQLixag2wEEn7FbBf9t3IEgJ0xuHq817g-zS8z5i0R2gIo5HR-vhAHiz73pImPEI2Xcnff3Sc7BAwqLsW5NwkUV7_ADX8L38N7A" data-noaft="1" jsname="HiaYvf" jsaction="load:XAeZkd;" style="width: 40px; height: 40px; margin: 0px;"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/community">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/community/create/">NEW REVIEW</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    {% block body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>